[package]
name = "tower-minify-html"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A Tower layer for minifying HTML responses using minify-html"
repository = "https://github.com/avsaase/tower-minify-html"
keywords = ["tower", "middleware", "html", "minify", "axum"]
categories = ["web-programming", "middleware"]

[workspace]
members = ["examples/axum"]

[dependencies]
bytes = "1.11.0"
http = "1.4.0"
http-body-util = "0.1.3"
minify-html = "0.18.1"
tower = "0.5.2"
tracing = "0.1.44"
